### ISSUE TITLE
[Metrics] Dashboard v1

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#169]
This epic is for tracking the deployment of first version of the metrics dashboard, including the metrics selected in https://docs.google.com/spreadsheets/d/1SH7B8YOHArkKp7OF4qPnUuh2Rit_syVaOfjbbFWqmXw/edit#gid=0 (those highlighted in green)

## Acceptance Criteria

```[tasklist]
### Tasks
- [ ] https://github.com/edx/edx-arch-experiments/issues/223
- [ ] https://github.com/edx/edx-arch-experiments/issues/224
- [ ] https://github.com/edx/edx-arch-experiments/issues/225
- [ ] https://github.com/edx/edx-arch-experiments/issues/301
- [ ] https://github.com/edx/edx-arch-experiments/issues/167
- [ ] https://github.com/edx/edx-arch-experiments/issues/168
```

It's possible we may want to use a third party tool for this, like one of the ones mentioned in https://github.com/edx/edx-arch-experiments/issues/84 . We may want to make separate tickets for creating a POC using one or more of the tools there before proceeding with a full roll out.
For each product, answer:
1. Do you measure the 5 things? (reliability, frequency of deployments, MTTR, code review timing, CFR)
2. How much does it cost?
3. What's the setup process? Do you integrate with the stuff we use (GoCD, argoCD, JIRA, GitHub)
4. Do you have an example dashboard?

**Comment by adzuci** [comment]
@rgraber Should we close this epic or mark it as not prioritized.  Also, would any of the discovery work be relevant for the "Standardization & Metrics" initiative mentioned on slide 14 of https://drive.google.com/file/d/1fUwJ_TU3MncKqSmOwk058OrLL1vQjSvm/view ?



![Image](https://github.com/edx/edx-arch-experiments/assets/278814/083d8690-132a-47c0-ae46-662aeb455b7a)

**Comment by jristau1984** [comment]
I have moved reference of this epic to Confluence: https://2u-internal.atlassian.net/wiki/spaces/AT/pages/1154875404/BOM+Epic+Proposals

I have confirmed all linked takss have the Metrics epic applied, as does this ticket for historical reference.  I am closing this ticket as replaced by the Epics custom project field.
