### ISSUE TITLE
[Event Bus] Reduce operation and onboarding effort

### ISSUE THREAD

**Issue by jmbowman** [edx/edx-arch-experiments#183]
Last quarter we successfully deployed the event bus and its first use case in production, and ensured that we could rely on it and recover from any problems.  But there were still a few recurring problems that incurred extra maintenance work and some gaps in documentation that posed stumbling blocks for other people starting to consider the event bus for their own use cases.  This issue collects the work we're doing in this quarter to resolve those underlying issues, reducing the effort needed to keep the event bus operating smoothly and employ it for new tasks.

```[tasklist]
### Tasks
- [x] https://github.com/openedx/openedx-events/issues/159
- [x] https://github.com/edx/edx-arch-experiments/issues/158
- [x] https://github.com/openedx/openedx-events/issues/162
- [x] https://github.com/edx/edx-arch-experiments/issues/172
- [x] https://github.com/openedx/openedx-events/issues/178
- [x] https://github.com/openedx/event-bus-kafka/issues/116
- [x] https://github.com/openedx/openedx-events/pull/172
- [x] https://github.com/openedx/openedx-events/pull/168
- [ ] https://github.com/openedx/event-bus-kafka/issues/124
- [ ] https://github.com/openedx/event-bus-kafka/issues/111
- [ ] https://github.com/edx/edx-arch-experiments/issues/162
- [ ] https://github.com/edx/edx-arch-experiments/issues/178
- [ ] https://github.com/edx/edx-arch-experiments/issues/196
- [ ] https://github.com/openedx/event-bus-kafka/issues/135
```
