### ISSUE TITLE
Complete edx-sphinx-theme DEPR in edx org

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#339]
**AC:**
- [ ] Usage of edx-sphinx-theme in the edx org has been removed.

**Additional Notes:**
- DEPR: https://github.com/openedx-unsupported/edx-sphinx-theme/issues/184
- Instructions: https://docs.openedx.org/en/latest/developers/how-tos/switch-to-the-sphinx-book-theme.html
- The repos in the edx GitHub org that still depend on this theme:

```[tasklist]
### Tasks
- [x] [braze-client](https://github.com/edx/braze-client/pull/29)
- [x] [commerce-coordinator](https://github.com/edx/commerce-coordinator/pull/259)
- [x] [dbt-schema-builder](https://github.com/edx/dbt-schema-builder/pull/98)
- [x] [demographics](https://github.com/edx/demographics/pull/380)
- [x] [edx-arch-experiments](https://github.com/edx/edx-arch-experiments/pull/763)
- [x] [edx-exams](https://github.com/edx/edx-exams/issues/299)
- [x] [edx-name-affirmation](https://github.com/edx/edx-name-affirmation/issues/208)
- [x] [financial-assistance](https://github.com/edx/financial-assistance/issues/54)
- [x] [getsmarter-api-clients](https://github.com/edx/getsmarter-api-clients/issues/23)
- [x] [learner-pathway-progress](https://github.com/edx/learner-pathway-progress/pull/25)
- [x] [monitoring-scripts](https://github.com/edx/monitoring-scripts/pull/128)
- [x] [outcome-surveys](https://github.com/edx/outcome-surveys/pull/20)
- [x] platform-plugin-coaching (unable to write to this and forking is also disabled)
- [x] [platform-plugin-notices](https://github.com/edx/platform-plugin-notices/pull/220)
- [x] [portal-designer](https://github.com/edx/portal-designer/issues/337)
- [x] [program-intent-engagement](https://github.com/edx/program-intent-engagement/pull/138)
- [x] [subscriptions](https://github.com/edx/subscriptions/pull/209)
- [x] [video-encode-manager](https://github.com/edx/video-encode-manager/pull/460)
```

- The common constraint was removed, but we think that upgrades _may_ be picking up the right version for some reason, which is good. Otherwise, this constraint would need to be copied into the other repos. See https://github.com/openedx-unsupported/edx-sphinx-theme/issues/184
  - I closed the ticket to remove this common constraint: https://github.com/openedx/edx-lint/issues/338

**Comment by huniafatima-arbi** [comment]
We are waiting on the information to be added in license and author section which is to be updated as the `edx-sphinx-theme` is being replaced by `sphinx-book-theme`. 
[Slack thread for more information](https://twou.slack.com/archives/C04B987KHK5/p1728906553784519).
Moving it to blocked until the issue is resolved.

**Comment by MichaelRoytman** [comment]
@huniafatima-arbi I hope you're doing well. I think that the upgrade of `sphinx` may have broken the requirements in the repository, as there is now a conflict between `doc8`, `readme-renderer`, and `sphinx` on the version of `docutils`. [This causing the Python requirements upgrade action to fail](https://github.com/edx/edx-name-affirmation/actions/runs/11839306155/job/32990423171#step:6:628).

Here is the error log.

```
pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('docutils<=0.21.2,>=0.19'), parent=LinkCandidate('https://files.pythonhosted.org/packages/0c/f1/6ffd5d76578e98a8f21ae7216b88a7212c778f665f1a8f4f8ce6f9605da4/doc8-1.1.2-py3-none-any.whl (from https://pypi.org/simple/doc8/) (requires-python:>=3.8)')), RequirementInformation(requirement=SpecifierRequirement('docutils>=0.21.2'), parent=LinkCandidate('https://files.pythonhosted.org/packages/e1/67/921ec3024056483db83953ae8e48079ad62b92db7880013ca77632921dd0/readme_renderer-44.0-py3-none-any.whl (from https://pypi.org/simple/readme-renderer/) (requires-python:>=3.9)')), RequirementInformation(requirement=SpecifierRequirement('docutils<0.20,>=0.14'), parent=LinkCandidate('https://files.pythonhosted.org/packages/67/a7/01dd6fd9653c056258d65032aa09a615b5d7b07dd840845a9f41a8860fbc/sphinx-5.3.0-py3-none-any.whl (from https://pypi.org/simple/sphinx/) (requires-python:>=3.6)'))]
```

- doc8 requires `docutils<=0.21.2,>=0.19`
- readme-renderer requires `docutils>=0.21.2`
- sphinx requires `docutils<0.20,>=0.14`

The earliest version of `sphinx` that supports `docutils>0.21.0` is `7.3.0`, but that causes conflicts with the `sphinx-book-theme` you added, because that requires `sphinx<7`.

I'm unable to find a combination of versions that allow us to successfully install requirements. Can you help me understand how to correct this issue while maintaining the changes you made? Thank you.

**Comment by huniafatima-arbi** [comment]
> [@huniafatima-arbi](https://github.com/huniafatima-arbi) I hope you're doing well. I think that the upgrade of `sphinx` may have broken the requirements in the repository, as there is now a conflict between `doc8`, `readme-renderer`, and `sphinx` on the version of `docutils`. [This causing the Python requirements upgrade action to fail](https://github.com/edx/edx-name-affirmation/actions/runs/11839306155/job/32990423171#step:6:628).
> 
> Here is the error log.
> 
> ```
> pip._vendor.resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=SpecifierRequirement('docutils<=0.21.2,>=0.19'), parent=LinkCandidate('https://files.pythonhosted.org/packages/0c/f1/6ffd5d76578e98a8f21ae7216b88a7212c778f665f1a8f4f8ce6f9605da4/doc8-1.1.2-py3-none-any.whl (from https://pypi.org/simple/doc8/) (requires-python:>=3.8)')), RequirementInformation(requirement=SpecifierRequirement('docutils>=0.21.2'), parent=LinkCandidate('https://files.pythonhosted.org/packages/e1/67/921ec3024056483db83953ae8e48079ad62b92db7880013ca77632921dd0/readme_renderer-44.0-py3-none-any.whl (from https://pypi.org/simple/readme-renderer/) (requires-python:>=3.9)')), RequirementInformation(requirement=SpecifierRequirement('docutils<0.20,>=0.14'), parent=LinkCandidate('https://files.pythonhosted.org/packages/67/a7/01dd6fd9653c056258d65032aa09a615b5d7b07dd840845a9f41a8860fbc/sphinx-5.3.0-py3-none-any.whl (from https://pypi.org/simple/sphinx/) (requires-python:>=3.6)'))]
> ```
> 
> * doc8 requires `docutils<=0.21.2,>=0.19`
> * readme-renderer requires `docutils>=0.21.2`
> * sphinx requires `docutils<0.20,>=0.14`
> 
> The earliest version of `sphinx` that supports `docutils>0.21.0` is `7.3.0`, but that causes conflicts with the `sphinx-book-theme` you added, because that requires `sphinx<7`.
> 
> I'm unable to find a combination of versions that allow us to successfully install requirements. Can you help me understand how to correct this issue while maintaining the changes you made? Thank you.

Hey @MichaelRoytman I have created an issue against this and added to board. We shall be picking this up and looking into this issue. 
Issue reference: https://github.com/edx/edx-name-affirmation/issues/231
thank you for pointing it out.
