### ISSUE TITLE
Reduce noise from large third party cookies

### ISSUE THREAD

**Issue by rgraber** [edx/edx-arch-experiments#374]
Context:
We have a few large cookies in our cookie headers that we are pretty sure we're not going to be able to get rid of or make smaller, mostly from third parties (eg StackAdapt). These larger cookies frequently cause a Large cookie header alert, which is annoying when we can't really do anything about it. They also may be diverting attention from other large cookies we can fix or remove.

Proposal:
Split the alerts into a lower threshold one for the size without these third party cookies and a higher threshold for the size with.

Implementation details:
```[tasklist]
### Tasks
- [ ] [Update middleware](https://github.com/openedx/edx-django-utils/issues/329)
- [ ] Increase COOKIE_HEADER_SIZE_LOGGING_THRESHOLD to 15K 
- [ ] Set COOKIE_HEADER_WITH_EXCLUSIONS_SIZE_LOGGING_THRESHOLD to 9K
- [ ] Change the Large cookie header alert to look at the new custom attribute
- [ ] Create a new alert (possibly a P1?) that alerts if the real size is over 15K
- [ ] Update the runbook to reflect the new alerts, and also note that if the real size is over 15K we may need to actually do something about the third party cookies
```

**Comment by robrap** [comment]
We are assuming this will be taken up by the new owning team when and if they decide to implement.

**Comment by jristau1984** [comment]
Closing since this is no longer under Arch-BOM ownership.

@kalebjdavenport would you like to port this to your team?
