### ISSUE TITLE
[Docs] Roadmap and milestone doc completion

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#42]
Acceptance Criteria:

- [x] Close out epic: https://2u-internal.atlassian.net/browse/ARCHBOM-2044
  - [x] Find home (task or doc) for lifecycle events: https://2u-internal.atlassian.net/browse/ARCHBOM-2008
  - [x] Find home (task or doc) for event evolution: https://2u-internal.atlassian.net/browse/ARCHBOM-2013
- [x] Address https://github.com/openedx/platform-roadmap/issues/28#issuecomment-1170524634
  - [x] "share links to the use cases and any other related design/specs"
- [x] Clean-up duplication in https://openedx.atlassian.net/wiki/spaces/AC/pages/3127869624/Event+Bus+Discovery+In+Progress

Other possibilities (do or ticket)
- [x] Timeline as it affects other squads and the community. (6 week deliverables?)
- [x] Diagram to help communicate status
- [x] Quick Confluence doc clean-up?
- [x] Create other doc related tickets.
- [x] Create issues or docs for the following:
    - Error handling on publishing/consuming side.
    - Dead letter queue, retries, etc.
    - Monitoring? 
       - Are consumer pods up?
       - Is the queue draining?
       - Current processing delay.
       - Do we want to be paged when a pod dies

**Comment by robrap** [comment]
Moving status communication to a separate ticket, and closing this.
