### ISSUE TITLE
Resolve celery Redis issue blocking edxapp deploys

### ISSUE THREAD

**Issue by robrap** [edx/edx-arch-experiments#799]
**Tasks:** 
- [X] Resolve issue and update RCA docs
- [X] Document follow-up tasks for SRE: https://2u-internal.atlassian.net/browse/DOS-5223
- [X] Update [DD Redis/Celery dashboard](https://2u-internal.atlassian.net/browse/DOS-5223) to be useful in the future.
- [X] Ensure communication is sent to teams (Alex D. is taking this.)
- [X] Ensure RCA is scheduled (Alex D. is taking this.)

The edxapp pipeline is blocked because celery and Redis are having issues for each deploy.

See [#incident-edx-celery-queue-issue](https://twou.slack.com/archives/C07M1QFD2HK) and [RCA: edX Celery Queuing issue](https://2u-internal.atlassian.net/wiki/spaces/ENG/pages/1325236431/RCA+edX+Celery+Queuing+issue) for details.
