### ISSUE TITLE
Final sweep of "TODO (EventBus)" in openedx and edx orgs

### ISSUE THREAD

**Issue by timmc-edx** [edx/edx-arch-experiments#80]
Ensure these are each removed or tasked (updating as needed).

From `ack 'todo.*event.*bus' -i` of all repos in all edx orgs:

- [x] https://github.com/openedx/openedx-events/pull/134
- [x] openedx/course-discovery -- contained a comment in some copied code, ignoring (will likely all be removed)
- [x] https://github.com/openedx/event-bus-kafka/pull/69
- [x] https://github.com/edx/edx-internal/pull/7322
- [x] https://github.com/edx/enterprise-access/pull/84

**Comment by timmc-edx** [comment]
Blocked on review of remaining PR.

**Comment by robrap** [comment]
@timmc-edx: See my approval comment: https://github.com/edx/enterprise-access/pull/84#pullrequestreview-1169267533. I still think you should inform Brian/Chris about the larger clean-up that they can do, but that doesn't need to block this ticket.

I can merge on Monday if you want to remind me. Not sure if they care about deployment, since it is just a change to comments.
